# Alacritty config options: https://alacritty.org/config-alacritty.html
# More about toml: https://toml.io/en/
import = ["/home/henrique/.config/alacritty/themes/rose-pine.toml"]

[window]
opacity = 0.8

[font.normal]
family = "FiraCodeNerdFont"
style = "Regular"

[font.bold]
family = "FiraCodeNerdFont"
style = "Bold"

[font.italic]
family = "FiraCodeNerdFont"
style = "Italic"

[font.bold_italic]
family = "FiraCodeNerdFont"
style = "Bold Italic"
